#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "headers/funcs.h"

void code(char input[32]){
    if(strstr(input,"AT6.c")){
        printf("\n#include <stdio.h>\n\nint main()\n{\n    int dia;\n    printf(¨Qual dia da semana é hoje?\n 0 = domingo\n 1 = segunda-feira\n 2 = terça-feira\n 3 = quarta-feira\n 4 = quinta-feira\n 5 = sexta-feira\n 6 =sábado.\n¨);\n    scanf(¨/d¨, &dia);\n    switch(dia){\n        case 0: printf(¨É dia fim de samana!!¨); break;\n        case 1: printf(¨Ainda é dia de trabalho :(¨); break;\n        case 2: printf(¨Ainda é dia de trabalho :(¨); break;\n        case 3: printf(¨Ainda é dia de trabalho :(¨); break;\n        case 4: printf(¨Ainda é dia de trabalho :(¨); break;\n        case 5: printf(¨Sextou!¨); break;\n        case 6: printf(¨É dia fim de samana!!¨); break;\n        default: printf(¨Número inválido¨); break;\n    }*/\n    switch(dia){\n        case 0: printf(¨É domingo! Hora de preocupar sobre segunda¨); break;\n        case 1: printf(¨Dia de semana: Segunda-Feira¨); break;\n        case 2: printf(¨Dia de semana: Terça-Feira¨); break;\n        case 3: printf(¨Dia de semana: Quarta-Feira¨); break;\n        case 4: printf(¨Dia de semana: Quinta-Feira¨); break;\n        case 5: printf(¨Sextou! Mas ainda é dia de semana¨); break;\n        case 6: printf(¨Sabadão fim de samana!¨); break;\n        default: printf(¨Número inválido¨); break;\n    }*/\n    if(dia > 0 && dia < 6){\n        if(dia==1){\n            printf(¨Dia de semana: Segunda-Feira¨);\n        }\n        else if(dia==2){\n            printf(¨Dia de semana: Terça-Feira¨);\n        }\n        else if(dia==3){\n            printf(¨Dia de semana: Quarta-Feira¨);\n        }\n        else if(dia==4){\n            printf(¨Dia de semana: Quinta-Feira¨);\n        }\n        else if(dia==5){\n            printf(¨Sextou! Mas ainda é dia de semana¨);\n        }\n    }\n    else if(dia == 0 || dia == 6){\n        if(dia == 0){\n            printf(¨É domingo! Hora de preocupar sobre segunda¨);\n        }\n        else if(dia == 6){\n            printf(¨Sabadão fim de samana!¨);\n        }\n    }\n    else {\n        printf(¨Número inválido¨);\n    }\n    return 0;\n}");
        romuexercs();
    } else if(strstr(input, "AT5.c")){
        printf("\n#include <stdio.h>      /* printf, NULL */       \n#include <math.h>\n\nint unit(int dest){\n    switch(dest){\n    case 1: printf(¨ milímetros¨); break;\n    case 2: printf(¨ centímetros¨); break;\n    case 3: printf(¨ decímetros¨); break;\n    case 4: printf(¨ metros¨); break;\n    case 5: printf(¨ decâmetros¨); break;\n    case 6: printf(¨ hectômetros¨); break;\n    case 7: printf(¨ quilômetros¨); break;\n    default: printf(¨Algo deu errado¨); break;\n}\n}\n\n\nint main (){         \n    int orig,dest;\n    float end1,dist;\n    printf(¨7 - Km (quilômetro)\n6 - Hm(hectômetro)\n5 - Dam(decâmetro)\n4 - M(metro)\n3 - Dm(decímetro)\n2 - Cm(centímetro)\n1 - Mm(milímetro)¨);\n    printf(¨\n\nConsiderando os números acima, digite NESSA ORDEM:\nDistância a ser convertida | Unidade original da distância | Unidade de destino da conversão¨);\n    printf(¨\nDigite-os separando com espaço (x y z).\n¨);\n    scanf(¨/f /d /d¨,&dist, &orig, &dest);\n    \n    if(dest < orig){\n        end1 = dist * (int)pow(10, orig - dest);\n        printf(¨/.1f¨,end1);\n        unit(dest);\n        return 1;\n    }\n    else{\n        if(dest > orig){\n            end1 = dist / (int)pow(10, dest - orig);\n            printf(¨/.3f¨,end1);\n            unit(dest);\n            return 2;\n        }\n        else if(dest == orig){\n            end1 = dest;\n            printf(¨/.1f¨,end1);\n            unit(dest);\n            return 3;\n        }\n        else{\n            printf(¨Input inválido¨);\n            unit(dest);\n            return 4;\n        }\n    }\n\n}");
        romuexercs();
    } else if(strstr(input, "AT3.c")){
        printf("\n#include <stdio.h>\n\nint main()\n{\n    int nu;\n    int res;\n    \n    printf(¨Número: ¨);\n    scanf(¨/d¨,&nu);\n    res = nu / 2;\n    \n    if(res==0){\n        printf(¨\nSeu número é par¨);\n    }\n    else{\n        printf(¨\nSeu número é ímpar¨);\n    }\n}");
        romuexercs();
    } else if(strstr(input, "float.c")){
        printf("\n#include <stdio.h>         \n                                \nint main (){   \n    \n    float n1;\n    char o;\n    float n2;\n    \n    printf(¨Digite sua operação desejada.\n¨);\n    scanf(¨/f /c /f¨, &n1, &o, &n2);\n    \n    switch(o){\n        case '/':\n            printf(¨/.2f / /.2f = /.2f¨,n1,n2,(n1 / n2));\n            break;\n        \n        case '*':\n            printf(¨/.2f * /.2f = /.2f¨,n1,n2,(n1 * n2));\n            break;\n        \n        case '-':\n            printf(¨/.2f - /.2f = /.2f¨,n1,n2,(n1 - n2));\n            break;\n        \n        case '+':\n            printf(¨/.2f + /.2f = /.2f¨,n1,n2,(n1 + n2));\n            break;\n        \n        default:\n        printf(¨\nOperador não suportado.¨);\n        break;\n    }\n}");
        calc();
    } else if(strstr(input, "bhask.c")){
        printf("\n#include <stdio.h>\n#include <math.h>\n\nint main()\n{\n    int a,b,c,delta,bhas1,bhas2;\n    \n    printf(¨digitet a b e c (ax2+bx+c)\n¨);\n    scanf(¨/d /d /d¨,&a,&b,&c);\n    \n    delta = (pow(b, 2) )- (4 * (a * c));\n    \n    printf(¨\n/d\n¨,delta);\n    \n    bhas1 = (-b+sqrt(delta)) / (2*a);\n    bhas2 = (-b-sqrt(delta)) / (2*a);\n    \n    printf(¨S={/d /d}¨,bhas1,bhas2);\n    \n\n    return 0;\n}");
        calc();
    } else if(strstr(input, "calc.c")){
        printf("\n#include <stdio.h>     \n\nint main (){                                \n    int n1;\n    char o;\n    int n2;\n    \n    printf(¨Digite a operação desejada.\n¨);\n    scanf(¨/d /c /d¨,&n1,&o,&n2);\n    \n    switch(o){\n        case '/':\n            printf(¨/d / /d = /d¨, n1, n2, (n1 / n2));\n            break;\n        case '*':\n            printf(¨/d * /d = /d¨, n1, n2, (n1 * n2));\n            break;\n        case '-':\n            printf(¨/d - /d = /d¨, n1, n2, (n1 - n2));\n            break;\n        case '+':\n            printf(¨/d + /d = /d¨, n1, n2, (n1 + n2));\n            break;\n        default:\n            printf(¨\nInput não suportado¨);\n    }\n}");
        calc();
    }
}
